CREATE DATABASE QL_KhachHang ON PRIMARY (
  NAME = Arch1,
  FILENAME = 'E:\QL_KhachHang1.mdf',
  SIZE = 100MB,
  MAXSIZE = 200,
  FILEGROWTH = 20
),
(
  NAME = Arch2,
  FILENAME = 'E:\QL_KhachHang2.ndf',
  SIZE = 100MB,
  MAXSIZE = 200,
  FILEGROWTH = 20
),
(
  NAME = Arch3,
  FILENAME = 'E:\QL_KhachHang3.ndf',
  SIZE = 100MB,
  MAXSIZE = 200,
  FILEGROWTH = 20
) LOG ON (
  NAME = Archlog1,
  FILENAME = 'E:\QL_KhachHang_log1.ldf',
  SIZE = 100MB,
  MAXSIZE = 200,
  FILEGROWTH = 20
),
(
  NAME = Archlog2,
  FILENAME = 'E:\QL_KhachHang_log2.ldf',
  SIZE = 100MB,
  MAXSIZE = 200,
  FILEGROWTH = 20
) USE QL_KhachHang CREATE TABLE tblKhachHang (
  MSKH CHAR(5),
  TenKH NVARCHAR(50) NOT NULL,
  DiaChi NVARCHAR(50),
  PRIMARY KEY (MSKH)
);
CREATE TABLE tblPhongBan (
  MaPB CHAR(2),
  TenPB NVARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (MaPB)
);
CREATE TABLE tblNhanVien (
  MSNV VARCHAR(5),
  TenNV NVARCHAR(50) NOT NULL,
  NgaySinh SMALLDATETIME NOT NULL,
  SoCMND CHAR(9) UNIQUE,
  GioiTinh CHAR(1) DEFAULT 'M',
  NgayVaoLam SMALLDATETIME,
  MaPB CHAR(2),
  CONSTRAINT NgaySinh CHECK (NgaySinh <= GetDate()),
  CONSTRAINT SoCMND CHECK (CAST(SoCMND AS BIGINT) > 0),
  CONSTRAINT GioiTinh CHECK (
    GioiTinh = 'F'
    OR GioiTinh = 'M'
  ),
  CONSTRAINT NgayVaoLam CHECK (YEAR(NgayVaoLam) - YEAR(NgaySinh) > 20),
  PRIMARY KEY (MSNV),
  FOREIGN KEY (MaPB) REFERENCES tblPhongBan(MaPB)
);
CREATE TABLE tblHoaDon(
  MSHD Char(4),
  NgayHD Smalldatetime,
  MSKH Char(5),
  MSNV VARCHAR(5),
  PRIMARY KEY (MSHD),
  FOREIGN KEY (MSKH) REFERENCES tblKhachHang(MSKH),
  FOREIGN KEY (MSNV) REFERENCES tblNhanVien(MSNV)
);
CREATE TABLE tblHangHoa (
  MSHH Char(4),
  TenHH NVARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (MSHH)
);
CREATE TABLE tblCTHoaDon (
  MSHD Char(4),
  MSHH Char(4),
  SoLuong INT DEFAULT 1,
  DonGia INT DEFAULT 10,
  PRIMARY KEY (MSHD, MSHH),
  FOREIGN KEY (MSHD) REFERENCES tblHoaDon(MSHD),
  FOREIGN KEY (MSHH) REFERENCES tblHangHoa(MSHH),
  CONSTRAINT SoLuong CHECK (SoLuong > 0),
  CONSTRAINT DonGia CHECK (DonGia > 0)
);